---
title: "parse_pages"
date: '2022-05-30'
---

```{r}
library(tidyverse)
library(pdftools)
library(anytime)
library(reticulate)
library(lubridate)
source_python("functions.py")
source("~/Projects/nixon-diary-extraction/functions.R")
```

```{r}
raw.1969 <- read_rds("1969.rds")
raw.1970 <- read_rds("1970.rds")
raw.1971 <- read_rds("1971.rds")
raw.1972 <- read_rds("1972.rds")
raw.1973 <- read_rds("1973.rds")
raw.1974 <- read_rds("1974.rds")
```



```{r}
toc_1969 <- build_toc("1969 Presidential Daily Diary.pdf")
toc_1970 <- build_toc("1970 Presidential Daily Diary.pdf")
toc_1971 <- build_toc("1971 Presidential Daily Diary.pdf")
toc_1972 <- build_toc("1972 Presidential Daily Diary.pdf")
toc_1973 <- build_toc("1973 Presidential Daily Diary.pdf")
toc_1974 <- build_toc("1974 Presidential Daily Diary.pdf")
```


```{r}
diary.1969 <- create.doc.lists(raw.1969, toc_1969)
diary.1970 <- create.doc.lists(raw.1970, toc_1970)
diary.1971 <- create.doc.lists(raw.1971, toc_1971)
diary.1972 <- create.doc.lists(raw.1972, toc_1972)
diary.1973 <- create.doc.lists(raw.1973, toc_1973)
diary.1974 <- create.doc.lists(raw.1974, toc_1974)
```

```{r}
all_items <- c(diary.1969, diary.1970, diary.1971, diary.1972, diary.1973, diary.1974)
all_items <- do.call(c, all_items)
all_items <- all_items[str_ends(names(all_items), 'data_frame')]
all_items <- data.frame(do.call("rbind", all_items))

all_items <- all_items %>% 
  mutate(across(where(is.character), str_squish)) %>% 
  mutate(activity = str_remove_all(activity, '^[^[:alpha:]]+')) %>% 
  mutate(activity = str_remove_all(activity, '[\\|—\\-!=><_:]')) %>% 
  filter(!(activity== "")) %>% 
  filter(!grepl( "—", time_in, fixed=TRUE)) %>% 
  #filters out junk characters
  filter(!(nchar(activity) < 6 & !grepl( "press", activity, ignore.case = TRUE))) %>% 
  #Filters out  accidental appendix grabs
  filter(!is.na(mdy(date, quiet = TRUE))) %>% 
  #Filters out mis-entries from printing office label
  filter(!(str_detect(time_in, "^19[67][91234]$") & grepl("-", time_out, fixed = TRUE))) %>% 
  filter(!str_detect(activity, "^[p|P]age"))

#Fixes 3s instead of colons
colon_3_check <- "(1[012]\\s*3[0-5][0-9])|([0-9]\\s*3[0-5][0-9])"
colon_3_check_in <- (str_detect(all_items$time_in, colon_3_check))
colon_3_check_out <- (str_detect(all_items$time_out, colon_3_check) & !is.na(all_items$time_out))
str_sub(all_items$time_in[colon_3_check_in],
        str_locate(all_items$time_in[colon_3_check_in], colon_3_check)[, 2] - 2,
        str_locate(all_items$time_in[colon_3_check_in], colon_3_check)[, 2] - 2) <- ':'

str_sub(all_items$time_out[colon_3_check_out],
        str_locate(all_items$time_out[colon_3_check_out], colon_3_check)[, 2] - 2,
        str_locate(all_items$time_out[colon_3_check_out], colon_3_check)[, 2] - 2) <- ':'

all_items$time_in <- str_replace(all_items$time_in, " :|: ", ":")
all_items$time_out <- str_replace(all_items$time_out, " :|: ", ":")



#If proper time stamp exists, replace string with that otherwise leave as is
only_time <- function(x) ifelse(identical((t <- str_extract_all(x, "(1[012]:[0-5][0-9])|([0-9]:[0-5][0-9])")[[1]]), character(0)), x, t)
all_items$time_in <- sapply(all_items$time_in, only_time)
all_items$time_out <- sapply(all_items$time_out, only_time)
```




```{r}
#Correct lines
strict_time <- "^(1[012]:[0-5][0-9])|([0-9]:[0-5][0-9])$"
time_in_check <- str_detect(all_items$time_in, strict_time)
time_out_check <- str_detect(all_items$time_out, strict_time) | is.na(all_items$time_out)
phone_check <- str_detect(all_items$phone, "^P|R$") | is.na(all_items$phone)
check <- time_in_check & time_out_check & phone_check
nrow(all_items[(check), ])
nrow(all_items[(check), ])/nrow(all_items)
View(all_items[!(check), ])

#There should be 2028 days, but only 2017 are represented in the dataset
all_items %>% count(date)
```




```{r}
View(all_items[str_detect(all_items$time_in, "^(1[012]:[0-5][0-9])|([0-9]:[0-5][0-9])$"), ])

View(all_items[(str_detect(all_items$time_in, "[:digit:]{1,2}:[:space:]$") & !is.na(all_items$time_out)), ])
```




TODO:
Fix time_out hour being in time_in
Fix years being recognized as times
Deal with items where there's just a line that is "The President:" and the next item is just names of meetings
Drop "The President Met with:" At end of lines